// Mocks generated by Mockito 5.4.6 from annotations
// in test_doodle/test/services_mocks/services_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:test_doodle/core/models/theme_model.dart' as _i7;
import 'package:test_doodle/core/models/transactions/transaction_model.dart'
    as _i5;
import 'package:test_doodle/core/services/theme_service.dart' as _i6;
import 'package:test_doodle/core/services/transaction_service/i_transaction_db_service.dart'
    as _i3;
import 'package:test_doodle/router/navigator_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake
    implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITransactionDBService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransactionDBService extends _i2.Mock
    implements _i3.ITransactionDBService {
  @override
  _i4.Future<List<_i5.TransactionModel>> getAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, []),
            returnValue: _i4.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.TransactionModel>>.value(
                  <_i5.TransactionModel>[],
                ),
          )
          as _i4.Future<List<_i5.TransactionModel>>);

  @override
  _i4.Future<List<_i5.TransactionModel>> getTransactionsByCategory({
    required bool? isExpense,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByCategory, [], {
              #isExpense: isExpense,
            }),
            returnValue: _i4.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.TransactionModel>>.value(
                  <_i5.TransactionModel>[],
                ),
          )
          as _i4.Future<List<_i5.TransactionModel>>);

  @override
  _i4.Future<int> insertTransaction(_i5.TransactionModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [model]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<double> getTotalAmount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalAmount, []),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<int> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> updateTransaction(_i5.TransactionModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ThemeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeService extends _i2.Mock implements _i6.ThemeService {
  @override
  _i4.Stream<_i7.ThemeModel> get themeStream =>
      (super.noSuchMethod(
            Invocation.getter(#themeStream),
            returnValue: _i4.Stream<_i7.ThemeModel>.empty(),
            returnValueForMissingStub: _i4.Stream<_i7.ThemeModel>.empty(),
          )
          as _i4.Stream<_i7.ThemeModel>);

  @override
  _i7.ThemeModel get theme =>
      (super.noSuchMethod(
            Invocation.getter(#theme),
            returnValue: _i7.ThemeModel.light,
            returnValueForMissingStub: _i7.ThemeModel.light,
          )
          as _i7.ThemeModel);

  @override
  _i4.Future<void> initTheme({required _i7.ThemeModel? systemTheme}) =>
      (super.noSuchMethod(
            Invocation.method(#initTheme, [], {#systemTheme: systemTheme}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changeTheme(_i7.ThemeModel? newTheme) =>
      (super.noSuchMethod(
            Invocation.method(#changeTheme, [newTheme]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NavigatorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorService extends _i2.Mock implements _i8.NavigatorService {
  @override
  _i1.GlobalKey<_i1.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_0<_i1.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_0<_i1.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i1.GlobalKey<_i1.NavigatorState>);

  @override
  _i4.Future<dynamic> goTo(String? routeName, {dynamic arguments}) =>
      (super.noSuchMethod(
            Invocation.method(#goTo, [routeName], {#arguments: arguments}),
            returnValue: _i4.Future<dynamic>.value(),
            returnValueForMissingStub: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  void goBack([dynamic arguments]) => super.noSuchMethod(
    Invocation.method(#goBack, [arguments]),
    returnValueForMissingStub: null,
  );
}
